version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - mvn clean package
      - mvn test
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - target/capstone-quotes-and-policy.jar
  discard-paths: yes